services:
  # خدمة الـ Backend
  api:
    build: ../node-express-realworld-example-app # تأكد من المسار الصحيح لفولدر الباكيند
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb?schema=public
      - NODE_ENV=development
    depends_on:
      - db

  # خدمة قاعدة البيانات
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # خدمة الـ Frontend (الجديدة)
  frontend:
    build: ../react-redux-realworld-example-app # المسار لفولدر الفرونت إيند
    ports:
      - "4100:80" # هنفتح الموقع على بورت 4100
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000/api # عشان الفرونت يعرف يكلم الباك
    depends_on:
      - api

volumes:
  postgres_data:
